In [ ]:
============================EDA===============================
1) pandas                    : Data frame or data application 
2) numpy                     : numerical python for math operation
3) matplotlip                : for plots graphs
4) seaborn                   : for plots graphs
5) Bokhe                     : for plots
6) plotly                    : for plots

==========================Machine learning=======================

7) scikit learn(sklearn)    : ML models
8) stats                    : statistical models

==========================Data retrival from sql scrapping ===========
9) sqlite                  : connect with database
10) Beautiful soup         : scrap the data from website
11) websocket              : scrap

========================Deep learning/ computer vision=================================
12) tensorflow             : Google 
13) keras                  : DL models
14) openCV                 : image operation
15) pillow(PIL)            : image operation
16) pytorch                : Facebook
17) pretrained models
       VGG16
       Mobilenet
       RESNET
       RCNN
       MASKRCNN
       FASTERCNN
       YOLO
=======================Natural language process============================
18) NLTK                : natural language process
19) Scipy
20) word2vec(How words will convert into vector ):
21) GloVE
22) Worldcloud

=========================Hugging face========================================
23) Transformers          :  BERT

==========================GenAI models===========================================
24) openAI+Microsoft      : GPT models
25) Google                : Gemini
26)  Amazon               :Q
27) Meta Facebook         :Meta AI
28 Apple                  : 

LLMA
GEMMA
Dalle-E
T5

ALL ARE HAVING DIFFERENT DIFFERENT PACKAGES

=============================LANGCHAIN================================
29) LangChain framework
============================deployments===============================
30) flask
31) Streamlit
32) Django

============================MLops=======================================
33) Mlflow
34) kubeflow
35) azure Ai services       : azure packages
36) GCP                     : GCP packages

**Step-1**

**Create a data frame**

- we will create a data frame using list

- we will create a dataframe using dictionary

In [1]:
import pandas as pd

In [3]:
d1=pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [4]:
type(d1)

pandas.core.frame.DataFrame

**step-2**

**provide the data**

In [5]:
names=['tarun','surender','mohith']
pd.DataFrame(names)

0
0     tarun
1  surender
2    mohith

In [6]:
names=['tarun','surender','mohith']
age=[20,21,22]
data=zip(names,age)
pd.DataFrame(data)

0   1
0     tarun  20
1  surender  21
2    mohith  22

In [7]:
names=['tarun','surender','mohith']
age=[20,21,22]
city=['hyd','ecil','blr']
pd.DataFrame(zip(names,age,city))

0   1     2
0     tarun  20   hyd
1  surender  21  ecil
2    mohith  22   blr

**step-3**

**provide the column names**

In [2]:
import pandas as pd
names=['tarun','surender','mohith']
pd.DataFrame(names,
             columns=['Names'])

Names
0     tarun
1  surender
2    mohith

In [10]:
names=['tarun','surender','mohith']
age=[22,25,24]
pd.DataFrame(zip(names,age),
             columns=['names','age'])

names  age
0     tarun   22
1  surender   25
2    mohith   24

In [11]:
names=['tarun','surender','mohith']
age=[22,25,24]
city=['hyd','blr','mum']
data=zip(names,age,city)
cols=['Name','age','city']
pd.DataFrame(zip(names,age,city),
             columns=['names','age','city'])

names  age city
0     tarun   22  hyd
1  surender   25  blr
2    mohith   24  mum

In [ ]:
names=['tarun','surender','mohith']
age=[22,25,24]
city=['hyd','blr','mum']
data=zip(names,age,city)
cols=['Name','age','city']
pd.DataFrame(zip(names,age,city),
             columns=['names','age','city'])

**step-4**

**prividing index**

In [14]:
names=['tarun','surender','mohith']
age=[22,25,24]
city=['hyd','blr','mum']

data=zip(names,age,city)
ix=['A','B','C']
cols=['Name','age','city']
pd.DataFrame(data,
             index=ix,
             columns=cols)

Name  age city
A     tarun   22  hyd
B  surender   25  blr
C    mohith   24  mum

In [6]:
import pandas as pd

In [ ]:
names=['tarun','surendar','mohith']
pd.DataFrame(names)
names=['tarun','surendar','mohith']
pd.DataFrame(names,
columns=['Names'])
# Why names is passing in list format if we have 1 column only--
##################################################################
names=['tarun','surendar','mohith']
age=[20,21,22]
pd.DataFrame(zip(names,age),
columns=['Names','Age'])
#############################################
names=['tarun','surendar','mohith']
age=[20,21,22]
city=['Hyd','ECIL','Blr']
data=zip(names,age,city)
cols=['Names','Age','City']
pd.DataFrame(data,columns=cols)
name = ['Tarun', 'Venkat', 'Sahasra']
age = [20, 35, 12]
city = ['Hyd', 'Blr', 'Chn']

In [10]:
name = ['Tarun', 'Venkat', 'Sahasra']
age = [20, 35, 12]
city = ['Hyd', 'Blr', 'Chn']
data = zip(name, age)
column=['Name', 'Age']
df=pd.DataFrame(data, index=city, columns=column)

In [11]:
df

Name  Age
Hyd    Tarun   20
Blr   Venkat   35
Chn  Sahasra   12

- create a dataframe
- provide the data 
- add the column
- provide the column names
- provide the index

**step-5**

**add a new column on existing data frame**

In [1]:
# create a data frame with name age and city
# Name
# age
# city


In [2]:
import pandas as pd

In [7]:
names=['Azad','ashish','aeyman']
age=[20,26,30]
city=['hyd','Patna','dubai']
data=zip(names,age,city)
cols=['Names','Age','City']
df=pd.DataFrame(data,columns=cols)
df

Names  Age   City
0    Azad   20    hyd
1  ashish   26  Patna
2  aeyman   30  dubai

- if you want to add a new column
- first chek how many rows are there
- for example in above dataframe we have 3 rows
- your new column also should have 3 rows
- suppose i want to create a new column: **salary**
- make a list with 3 values
- salary =[100000,200000,3000000]
**syntax**:  dataframe[column]=list of values
- df['salary']=salary

In [8]:
salary=[100000,20000,30000]
df['salary']=salary
df

Names  Age   City  salary
0    Azad   20    hyd  100000
1  ashish   26  Patna   20000
2  aeyman   30  dubai   30000

**use case-1**

- create empty data frame first
- create 3 list using list comprehension
- list1=a values from 1 to 10
- list2=square of 1 to 10 
- list3=cube of 1 to 10
- finally make a dataframe

In [3]:
import pandas as pd
df1=pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [4]:
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range (1,10)]
df1['x']=l1
df1['y']=l2
df1['z']=l3
df1

x   y    z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

**step-6**

**update the already existed column**

- create a new column
   - creating a new list salary=[10000,20000,30000]
   - df['s']
   - creating a new column name is our choice
- update existing column are same way only
- here also we need a make a list of values=numbner of rows
- while updating the existing column
- we need to provide already existed column name only
- df['z']=list of values

In [5]:
# dataframe name:df1
# list of values variable name:z
# which column we want to update: 'z'
z=[i**4 for i in range(1,10)]
df1['z']=z
df1

x   y     z
0  1   1     1
1  2   4    16
2  3   9    81
3  4  16   256
4  5  25   625
5  6  36  1296
6  7  49  2401
7  8  64  4096
8  9  81  6561

In [6]:
df2=pd.DataFrame()
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range (1,10)]

df2['number']=l1
df2['square']=l2
df2['cube']=l3
df2

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

**step-7**

**drop the column**

In [10]:
# how to chek the columns
df1.columns

Index(['x', 'y', 'z'], dtype='object')

- if you want to drop  specific column
- we will use drop method
- we already know about difference between keyword and methods
- keyword will use directly 
- Method will use with corresponding dataframe
- **method name: drop**

df1.drop()

- Column: which column you want to drop 
- axis: Represent the specified values is a row or column
  - axis=0 means rows
  - axis=1 means column

- inplace: will provide overwrite the dataframe or not
  - inplace =True, this indicates overwrite the dataframe
   - inplace= False, this indicates the modified dataframe will be use when you provide new variable for the operation 

In [8]:
df1.drop('x')
# we are not providing axis
# it assuming the provided values is a row 
# by defalut 

KeyError: "['x'] not found in axis"

In [9]:
df1.drop('x',axis=1)
# after this in a new cell type 
# you will see original dataframe
# because we did not provide inplace

# if you want to use 

y     z
0   1     1
1   4    16
2   9    81
3  16   256
4  25   625
5  36  1296
6  49  2401
7  64  4096
8  81  6561

In [11]:
df1.drop('x',axis=1,inplace=True)
df1

y     z
0   1     1
1   4    16
2   9    81
3  16   256
4  25   625
5  36  1296
6  49  2401
7  64  4096
8  81  6561

In [12]:
# read the data frame
# Provide the data
# Provide the column names
# Change the index
# Add the new column
# Modify the existing column
# Drop the column
# axis inplace
# You need to create a new column
# Drop the old column

**step-8**

**drop the row**

- drop the column and drop the rows both are similar only
- the are difference in axis
  - axis=0 represents rows
  - by default axis=0 available
  - which means if we provide any value, it will represent rows only

In [13]:
# Dataframe name: df1
import pandas as pd
df2=pd.DataFrame()
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]

df2['Number']=l1
df2['Square']=l2
df2['Cube']=l3

df2

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

In [14]:
df2.drop(4)
# If we run this we will get error
# by default axis=0 which represents about rows
# But 'Number' is a column
# If you want to drop row, the provide the row index

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

In [21]:
# Multiple rows
# Multiple columns keep always in a list
df2.drop([4,8])

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512

In [22]:
df2.columns[[0,1]]

Index(['Number', 'Square'], dtype='object')

In [17]:
df2.drop([0,1],axis=1)
# [0,1] index
# axis=1 columns
# error

KeyError: '[0, 1] not found in axis'

**step-9**

**how to select the column**

In [25]:
df2['Square']

# Series type
# no column name display
# when ever you see this type: Series type

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
Name: Square, dtype: int64

In [26]:
df2[['Square']]
# Data frame 

Square
0       1
1       4
2       9
3      16
4      25
5      36
6      49
7      64
8      81

**y**

In [28]:
type(df2['Number'])

pandas.core.series.Series

In [29]:
type(df2[['Number']])

pandas.core.frame.DataFrame

In [30]:
df2.Number

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: Number, dtype: int64

- df2['Number']: series type
- df2[['Number']]: Dataframe type
- df2.Number: Series type

In [31]:
cols=['Number', 'Square']
df2[cols]

Number  Square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81

In [32]:
df2['Number'].values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

- all values comes in an array
- array means it is a list of elements only represent using numpy package
- Generally elemenmts present in 3 ways
- list: basic representation
- Numpy arrays: Array with Numpy package
- Tensors: tensorflow package
- Torch: pytorch package

In [30]:
list1=[1,2,3,4]
list1

[1, 2, 3, 4]

In [36]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4])

In [37]:
#tensor([1,2,3,4])

In [38]:
list1=[1,2,3,4]
list2=[10,20,30,40]
list1+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [39]:
l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([11, 22, 33, 44])

In [ ]:
# 3 days every one hour : numpy
# A new package in the market: numpy
# you know python

# 

In [40]:
df2['Number'].values
# Imagine we worked on an ML problem
# We got some series of values
# with that series of values also we can create a dataframe

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [41]:
df2['Number']=df2['Number'].values
df2

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

**step-10**

**save the dataframe**

- DataFrame we can save in two formats
  - csv : comma saparated values
  - xlsx : excel format

- in order to save any data
  - where you want to save the directory name
  - what is the name of the file for storing
  - what is the extensions
- we already seen same thing in file handling session

In [ ]:
# case-1: saving file at the same location
# 
# no need to provide directory path
# Directly give name of the file
# and extension

In [42]:
# Dataframe = df2
df2.to_csv('Data1.csv')
df2.to_excel('Data1.xlsx')

**step-11 how to read the dataframe**

In [43]:
import pandas as pd
pd.read_csv('data1.csv')

Unnamed: 0  Number  Square  Cube
0           0       1       1     1
1           1       2       4     8
2           2       3       9    27
3           3       4      16    64
4           4       5      25   125
5           5       6      36   216
6           6       7      49   343
7           7       8      64   512
8           8       9      81   729

In [44]:
import os
os.getcwd()

'C:\\Users\\md mumtaz\\Documents\\Naresh it'

In [45]:
import pandas as pd
pd.read_excel('Data1.xlsx')

Unnamed: 0  Number  Square  Cube
0           0       1       1     1
1           1       2       4     8
2           2       3       9    27
3           3       4      16    64
4           4       5      25   125
5           5       6      36   216
6           6       7      49   343
7           7       8      64   512
8           8       9      81   729

**step-12:**

**how to avoid index column**

- while we save the dataframe
    
- automatically a new column will be create

- that we need to avoid

- permission denied means close the data file from laptop

In [47]:
# Dataframe name: df2
#save the data without index column
df2.to_csv('Data1.csv',index=False)
df2.to_excel('Data1.xlsx', index=False)

In [48]:
# read the data 
import pandas as pd
pd.read_csv('Data1.csv')

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729